language: ruby

install:
  - gem install html-proofer

script:
  # Google Scholar returns 403, ignore response
  # LinkedIn returns 999 status, ignore response
  # Only fail for 4xx because UCL website checks fail because of a certificate issue
  - htmlproofer --check-html --http-status-ignore 403,999 --url-ignore "#" --only-4xx --check-opengraph --check-img-http --check-sri --log-level debug
